title: Notre-Dame de Paris
baseURL: https://example.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 4
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Home
    weight: 1
  es:
    contentDir: content/es
    title: Inicio
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: Mario Mingarro's personal website
  facebook: ''
  favicon: ''
  featured_image: /images/A.jpg
  github: https://github.com/MarioMingarro
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: https://twitter.com/Minglop
  youtube: ''
